output_dir=/dccstor/myu/experiments/eli5_cmsks_embed_hop2_ctx3_greedy_3e05_0804
jbsub -q x86_24h -cores 10+1 -mem 40g -require 'a100_80gb' -proj 'eli5' -name 'cp_score_hop2_greedy' -o ${output_dir}/train.log \
python /dccstor/myu/primeqa/examples/lfqa_kb/run_cmsks_learn_embed.py \
  --model_name_or_path facebook/bart-large \
  --train_file /dccstor/myu/data/kilt_eli5_dpr/eli5-train-kilt-dpr.json \
  --validation_file /dccstor/myu/data/kilt_eli5_dpr/eli5-dev-kilt-dpr.json \
  --question_column input \
  --answer_column output \
  --context_column passages \
  --do_train \
  --do_eval \
  --fp16 \
  --per_device_train_batch_size 32 \
  --per_device_eval_batch_size 32 \
  --gradient_accumulation_steps 1 \
  --learning_rate 3e-5 \
  --num_train_epochs 3 \
  --max_seq_length 256 \
  --max_answer_length 256 \
  --generation_max_length 256 \
  --predict_with_generate \
  --output_dir ${output_dir} \
  --overwrite_output_dir \
  --overwrite_cache \
  --evaluation_strategy epoch \
  --save_strategy epoch \
  --load_best_model_at_end \
  --metric_for_best_model rougeL \
  --save_total_limit 2 \
  --n_context 3 \
  --kg_file /dccstor/myu/experiments/knowledge_trie/eli5_openie_merge/id2kg.pickle \
  --preprocessing_num_workers 10 \
  --generation_num_beams 1 \